FROM debian:buster

# Switch to root user
# USER root

# ==> apt-get, to get the last version of packages
RUN apt-get update && apt-get upgrade -y

# ==> Install MariaDB server (MySQL)
RUN apt-get install mariadb-server -y

# RUN chmod 644 /etc/mysql/mariadb.conf.d/50-server.cnf

# COPY tools/50.cnf /etc/mysql/mariadb.conf.d/50-server.cnf


COPY tools/db_script.sh /
RUN chmod +x db_script.sh


EXPOSE 3306

ENTRYPOINT ["bash", "db_script.sh"]
