FROM debian:buster


RUN apt-get update -y && apt-get install mariadb-server -y

# COPY ./tools/50-server.cnf /etc/mysql/mariadb.conf.d/

COPY ./tools/db_script.sh /
RUN chmod +x db_script.sh
# RUN  service mysql start
# RUN ./db_script.sh
CMD ["./db_script.sh"]