FROM debian:buster

# Install required packages
RUN apt-get update && apt-get install -y php7.3 \
    php7.3-fpm php7.3-mysql mariadb-client \
    nginx curl

# Download WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

# Make wp-cli.phar executable and move to /usr/local/bin as 'wp'
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# Copy configuration files
COPY ./conf/script.sh /script.sh
COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/

# Set permissions on script.sh and create required directories
RUN chmod +x script.sh && \
    mkdir /run/php/ && \
    mkdir -p /var/www/html/wordpress && \
    chown -R www-data:www-data /var/www/html/wordpress
# COPY ./conf/

# Set the entrypoint to script.sh
CMD ["sh", "script.sh"]

# Start php-fpm7.3 and nginx
# CMD ["php-fpm7.3", "-R", "-F"]
